### ISSUE TITLE
NDK build error

### ISSUE THREAD

**Issue by Yehh22** [codehasan/dex2c#14]
I got the following error. What does it mean?

```
[WARNING ] dcc: ================================
"D:\AndroidSDK\ndk\26.2.11394342\build\..\prebuilt\windows-x86_64\bin\make.exe": Interrupt/Exception caught (code = 0xc00000fd, addr = 0x00007ff684dc9950)
[ERROR   ] dcc: Compile F:\xxx.apk failed!
Traceback (most recent call last):
  File "F:\Github\dex2c\dcc.py", line 1017, in <module>
    dcc_main(
  File "F:\Github\dex2c\dcc.py", line 783, in dcc_main
    build_project(project_dir)
  File "F:\Github\dex2c\dcc.py", line 248, in build_project
    check_call([NDKBUILD, "-j%d" % cpu_count(), "-C", project_dir], stderr=STDOUT)
  File "D:\Python3\Lib\subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['D:/AndroidSDK/ndk/26.2.11394342\\ndk-build.cmd', '-j8', '-C', '.tmp\\dcc-project-zkaTk3xY']' returned non-zero exit status 255.
Command '['D:/AndroidSDK/ndk/26.2.11394342\\ndk-build.cmd', '-j8', '-C', '.tmp\\dcc-project-zkaTk3xY']' returned non-zero exit status 255.
[INFO    ] dcc: Restoring jni folder
[INFO    ] dcc: Removing .tmp folder
```

**Comment by AbhiTheModder** [comment]
HI, @Yehh22

Could you please provide full process logs, even though it seems like it's NDK related error, there might an issue occured with dex2c during the process so to make sure of that.

Also, It might be an issue the the version of NDK you're using, Recommended version of NDK: `26.1.10909125`

**Comment by AbhiTheModder** [comment]
@Yehh22 The start of your logs show:
```plaintext
[INFO    ] dcc: Creating .tmp folder
[INFO    ] dcc: Backing up jni folder
[WARNING ] androguard.core.api_specific_resources: Requested API level 31 is larger than maximum we have, returning API level 28 instead.
[WARNING ] dcc: compile method failed:Landroidx/vectordrawable/graphics/drawable/AnimationUtilsCompat;loadInterpolator(Landroid/content/Context;I)Landroid/view/animation/Interpolator; ()
```

The last line error:
>`[WARNING ] dcc: compile method failed:Landroidx/vectordrawable/graphics/drawable/AnimationUtilsCompat;loadInterpolator(Landroid/content/Context;I)Landroid/view/animation/Interpolator;`

This shows that you haven't defined filters carefully, Refer to [Usages#filters](https://github.com/codehasan/dex2c?tab=readme-ov-file#filters)

rather you're applying dex2c directly to the whole APK, which is not recommended on real world applications and usages, more so because applying on whole APK means you're basically applying it to each and every class,methods of inside DEX, which will cause the error for system related classes like `android/`, `androidx` etc.
