### ISSUE TITLE
Error while running with python 3.11

### ISSUE THREAD

**Issue by cxfshelter** [codehasan/dex2c#2]
Traceback (most recent call last):
  File "D:\project\newsvn\dsj\ours\tools\dex2c\dcc.cfg", line 9, in <module>
    "v1_enabled": true,
                  ^^^^
NameError: name 'true' is not defined. Did you mean: 'True'?

what's wrong?

**Comment by redragon14368** [comment]
> Traceback (most recent call last): File "D:\project\newsvn\dsj\ours\tools\dex2c\dcc.cfg", line 9, in "v1_enabled": true, ^^^^ NameError: name 'true' is not defined. Did you mean: 'True'?
> 
> what's wrong?
Open "D:\project\newsvn\dsj\ours\tools\dex2c\dcc.cfg" and look for ""v1_enabled": true," then try to make "true" to "True"

**Comment by codehasan** [comment]
Issue solved
