### ISSUE TITLE
Running script on Termux, file not found or missing

### ISSUE THREAD

**Issue by ghost** [codehasan/dex2c#31]
![160131](https://github.com/user-attachments/assets/d1bd6b77-aa9c-4499-8c1b-45629746e3d5)

By the way, can you make this project into a jar for use?
Scripts like this are available for running
https://github.com/luoyesiqiu/dpt-shell

**Comment by Uhugghbg** [comment]
@AbhiTheModder 
``pkg install wget && wget -O termux_install.sh https://raw.githubusercontent.com/codehasan/dex2c/master/termux_install.sh && chmod -R +x termux_install.sh && ./termux_install.sh``

The command website link for the install script seems to be lost,
Can you check and help further? Thanks
![48](https://github.com/user-attachments/assets/0146e6d6-5d40-4cb7-985f-aa63bfd4fdbf)

**Comment by AbhiTheModder** [comment]
> @AbhiTheModder `pkg install wget && wget -O termux_install.sh https://raw.githubusercontent.com/codehasan/dex2c/master/termux_install.sh && chmod -R +x termux_install.sh && ./termux_install.sh`
> 
> The command website link for the install script seems to be lost, Can you check and help further? Thanks 

It's perfectly fine,
![Screenshot_2024-11-05-21-31-23-386_com termux](https://github.com/user-attachments/assets/435438da-bd42-4c67-84b9-c684e2b2fb9f)

You're either on Play Store version of Termux(It's recommend to use Termux from GitHub or F-Droid) or on very low internet connection.
