### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by crowforkotlin** [codehasan/dex2c#40]
UnicodeEncodeError: 'charmap' codec can't encode character '\u4e28' in position 2: character maps to <undefined>
'charmap' codec can't encode character '\u4e28' in position 2: character maps to <undefined>

https://github.com/crowforkotlin/Dex2c-TestProject/blob/main/proguard-dict1.txt

dict contains char '丨' so it can't pass dex2c compile

Is there a way to support special characters?
![image](https://github.com/user-attachments/assets/da583766-7610-406d-834b-ddb483856b5e)

**Comment by AbhiTheModder** [comment]
Yet another windows cry, did the fix 7b70a8d3eb441c567581378a9b1109f96afae2d0, Please pull the latest changes, and it should work now. Also, note that the previous Windows fix has been merged into the master branch after your confirmation, so you can now use the master branch directly.
