### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by rufusin** [codehasan/dex2c#42]
Do you plan migrate from apktool to reandroid/apkeditor?

**Comment by AbhiTheModder** [comment]
Currently, there isn’t a specific need or reason to make this change, as Apktool’s recent updates have significantly improved its speed. However, if a situation arises where such a migration becomes necessary, we’ll consider it. Meanwhile, if you specifically need to use REAndroid's APKEditor, you can check out @Kirlif’s modifications to this repository: https://github.com/Kirlif/d2c. 

Thank you!
