### ISSUE TITLE
Error when running on termux (phone)

### ISSUE THREAD

**Issue by HuynhNgoc2709** [codehasan/dex2c#6]
On pc, I put in dcc.cfg "ndk_dir": "ndk-build", And I put the ndk-build folder in the dex2c folder, everything runs normally, but when I bring it up to termux (phone), I get an error that the ndk-build folder cannot be found.
![Screenshot_2023-10-01-04-13-09-880_com termux](https://github.com/ratsan/dex2c/assets/101563175/84dcdd4a-408c-43f6-bbbe-fac2254e3088)

**Comment by ratsan** [comment]
You can't run this in android for the time being.

**Comment by HuynhNgoc2709** [comment]
I was able to fix the error above, but error chmod

**Comment by codehasan** [comment]
Your issue will be fixed soon. We are adding guides to install dex2c in Termux specifically.
